global using System.ComponentModel.DataAnnotations;
global using AutoMapper;
global using EduAPI.Data.Entities;
global using EduAPI.Services.Models.DTOs;
global using Microsoft.AspNetCore.JsonPatch;
global using EduAPI.Data.DAL.Interfaces;
global using EduAPI.Services.Interfaces;
global using EduAPI.Services.Models.Exceptions;
global using Serilog;